import sys, subprocess, os

class ReportGenerator:
    def __init__(self):
        self.os_type = sys.platform

    def _copy_to_clipboard(self, text: str):
        """
        Cross-platform clipboard injection.
        optimized for macOS (pbcopy) on M4, but supports Windows (clip).
        """
        try:
            if self.os_type == "darwin":  # macOS
                process = subprocess.Popen(
                    'pbcopy', env={'LANG': 'en_US.UTF-8'}, stdin=subprocess.PIPE
                )
                process.communicate(text.encode('utf-8'))
            elif self.os_type == "win32": # Windows
                subprocess.run(['clip'], input=text.strip().encode('utf-16'), check=True)
            return True
        except Exception as e:
            print(f"   [WARN] Clipboard access failed: {e}")
            return False

    def generate_whatsapp_report(self, intern_name: str, stats: dict, flagged_items: list) -> str:
        """
        Generates a high-contrast, professional summary for Slack/WhatsApp.
        """
        total_files = stats['count']
        success_rate = (stats['SUCCESS'] / total_files * 100) if total_files > 0 else 0
        
        # Header
        report = []
        report.append(f"*AURA AUDIT REPORT v1.0*")
        report.append(f"👤 *Intern:* {intern_name}")
        report.append(f"📅 *Date:* {stats['date']}")
        report.append(f"--------------------------------")
        
        # Financials
        report.append(f"💰 *Total Verified:* ₹{stats['total_amt']:,.2f}")
        report.append(f"📂 *Files Scanned:* {total_files}")
        report.append(f"⚡ *Accuracy:* {success_rate:.1f}%")
        report.append(f"")
        
        # Breakdown
        report.append(f"*Session Breakdown:*")
        report.append(f"✅ Verified: {stats['SUCCESS']}")
        report.append(f"⚠️ Manual Review: {stats['MANUAL_REVIEW']}")
        report.append(f"❌ Duplicates: {stats['DUPLICATE']}")
        report.append(f"🚫 Failed: {stats['FAILED']}")

        # Flagged Item Details (Critical for feedback)
        if flagged_items:
            report.append(f"")
            report.append(f"*⚠️ FLAGGED ITEMS (Action Required):*")
            for item in flagged_items:
                reason = "DUPLICATE" if item['status'] == 'DUPLICATE' else "REVIEW"
                clean_name = item['file_name'][:20] + "..." if len(item['file_name']) > 20 else item['file_name']
                report.append(f"• {clean_name} -> *{reason}* (₹{item['amount']})")

        report.append(f"--------------------------------")
        report.append(f"_Generated by Project AURA on Apple Silicon_")
        
        final_text = "\n".join(report)
        
        # Auto-Copy
        if self._copy_to_clipboard(final_text):
            print(f"\n   [CLIPBOARD] ✅ Report copied! Ready to paste into WhatsApp.")
        else:
            print(f"\n   [CLIPBOARD] ❌ Auto-copy failed. Please manually copy the text above.")
            
        return final_text